git:
  depth: 1
sudo: required
services:
  - docker
language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn install --no-progress
script:
  - docker version
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
  - docker build -t ${DOCKER_USERNAME}/atlassian-connect-bitbucket:latest --rm=true -f Dockerfile . --pull=true
  - docker push ${DOCKER_USERNAME}/atlassian-connect-bitbucket
